services:
  ferretdb:
    container_name: ferretdb-floodme
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/ferretdb
    depends_on:
      - postgres
    networks:
      - ferret

  postgres:
    container_name: postgres-floodme
    hostname: postgres
    image: ghcr.io/ferretdb/postgres-documentdb:16
    restart: on-failure
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ferret

  mongo:
    container_name: mongo-floodme
    image: mongo
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  ferret:

volumes:
  pg:
