services:
  ferretdb-v1:
    image: ghcr.io/ferretdb/ferretdb:1
    restart: on-failure
    ports:
      - 27018:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
    networks:
      - v1

  postgres-v1:
    image: postgres
    hostname: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pg-v1:/var/lib/postgresql/data
    networks:
      - v1

  ferretdb:
    container_name: ferretdb-v2
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - v2

  postgres:
    container_name: postgres-v2
    hostname: postgres
    image: ghcr.io/ferretdb/postgres-documentdb:16
    restart: on-failure
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pg-v2:/var/lib/postgresql/data
    networks:
      - v2

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  v1:
    name: ferretdb-flooder-v1
  v2:
    name: ferretdb-flooder-v2

volumes:
  pg-v1:
    name: pg-v1
  pg-v2:
    name: pg-v2
